language: node_js
node_js:
  - "0.10.25"
script: node_modules/gulp/bin/gulp.js test
notifications:
  webhooks:
    urls:
      - "https://webhooks.gitter.im/e/9898d67dfc1dd39f9cb2"
    on_success: change
